// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiEdp36FoKxKRHzNtqZ1Y8CjUnj8CR5cE',
    appId: '1:823677183565:android:1dd916ffd0fa929b2a5e04',
    messagingSenderId: '823677183565',
    projectId: 'shtime-57731',
    storageBucket: 'shtime-57731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKJvpkAORQV0HiP6as8-W7U5juWhRjIU',
    appId: '1:823677183565:ios:ff78dc331a7f5b252a5e04',
    messagingSenderId: '823677183565',
    projectId: 'shtime-57731',
    storageBucket: 'shtime-57731.firebasestorage.app',
    androidClientId: '823677183565-264p65da2qq6l4dvqe61s6tbb9r7n0ok.apps.googleusercontent.com',
    iosClientId: '823677183565-mte35og76ek1fat5ffq3obi5mtf5bbij.apps.googleusercontent.com',
    iosBundleId: 'com.shomoshotime.shomoshotime',
  );

}